name: Setting up the paytm frontend
on: push

jobs:
  Build_Paytm_UI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: paytm/frontend/package-lock.json

      - name: install npm
        run: npm ci
        working-directory: paytm/frontend

      - name: Build Paytm Frontend
        run: npm run build
        working-directory: paytm/frontend

  BUILD_RECOIL:
    runs-on: ubuntu-latest
    needs: Build_Paytm_UI

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: recoil-react/package-lock.json

      - name: Install npm
        run: npm ci
        working-directory: recoil/

      - name: Build the recoil application
        run: npm run build
        working-directory: recoil/
